// search action types
export const UPDATE_SEARCH_PHRASE_REQUESTED = 'UPDATE_SEARCH_PHRASE_REQUESTED';
export const UPDATE_SEARCH_PHRASE_STARTED = 'UPDATE_SEARCH_PHRASE_STARTED';
export const UPDATE_SEARCH_PHRASE_SUCCEEDED = 'UPDATE_SEARCH_PHRASE_SUCCEEDED';
export const UPDATE_SEARCH_PHRASE_FAILED = 'UPDATE_SEARCH_PHRASE_FAILED';
export const UPDATE_SEARCH_PHRASE_FINISHED = 'UPDATE_SEARCH_PHRASE_FINISHED';

// user action types
export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
export const FETCH_USERS_STARTED = 'FETCH_USERS_STARTED';
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const FETCH_USERS_FINISHED = 'FETCH_USERS_FINISHED';
