// search action types
export const UPDATE_SEARCH_PHRASE_REQUESTED = 'UPDATE_SEARCH_PHRASE_REQUESTED';
export const UPDATE_SEARCH_PHRASE_STARTED = 'UPDATE_SEARCH_PHRASE_STARTED';
export const UPDATE_SEARCH_PHRASE_SUCCEEDED = 'UPDATE_SEARCH_PHRASE_SUCCEEDED';
export const UPDATE_SEARCH_PHRASE_FAILED = 'UPDATE_SEARCH_PHRASE_FAILED';
export const UPDATE_SEARCH_PHRASE_FINISHED = 'UPDATE_SEARCH_PHRASE_FINISHED';

// users action types
export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
export const FETCH_USERS_STARTED = 'FETCH_USERS_STARTED';
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const FETCH_USERS_FINISHED = 'FETCH_USERS_FINISHED';

// user action types
export const FETCH_USER_INFO_REQUESTED = 'FETCH_USER_INFO_REQUESTED';
export const FETCH_USER_INFO_STARTED = 'FETCH_USER_INFO_STARTED';
export const FETCH_USER_INFO_SUCCEEDED = 'FETCH_USER_INFO_SUCCEEDED';
export const FETCH_USER_INFO_FAILED = 'FETCH_USER_INFO_FAILED';
export const FETCH_USER_INFO_FINISHED = 'FETCH_USER_INFO_FINISHED';

// repositories action types
export const FETCH_REPOSITORIES_REQUESTED = 'FETCH_REPOSITORIES_REQUESTED';
export const FETCH_REPOSITORIES_STARTED = 'FETCH_REPOSITORIES_STARTED';
export const FETCH_REPOSITORIES_SUCCEEDED = 'FETCH_REPOSITORIES_SUCCEEDED';
export const FETCH_REPOSITORIES_FAILED = 'FETCH_REPOSITORIES_FAILED';
export const FETCH_REPOSITORIES_FINISHED = 'FETCH_REPOSITORIES_FINISHED';

// repository action types
export const FETCH_REPO_INFO_REQUESTED = 'FETCH_REPO_INFO_REQUESTED';
export const FETCH_REPO_INFO_STARTED = 'FETCH_REPO_INFO_STARTED';
export const FETCH_REPO_INFO_SUCCEEDED = 'FETCH_REPO_INFO_SUCCEEDED';
export const FETCH_REPO_INFO_FAILED = 'FETCH_REPO_INFO_FAILED';
export const FETCH_REPO_INFO_FINISHED = 'FETCH_REPO_INFO_FINISHED';

// repository contributors action types
export const FETCH_REPO_CONTRIBUTORS_REQUESTED = 'FETCH_REPO_CONTRIBUTORS_REQUESTED';
export const FETCH_REPO_CONTRIBUTORS_STARTED = 'FETCH_REPO_CONTRIBUTORS_STARTED';
export const FETCH_REPO_CONTRIBUTORS_SUCCEEDED = 'FETCH_REPO_CONTRIBUTORS_SUCCEEDED';
export const FETCH_REPO_CONTRIBUTORS_FAILED = 'FETCH_REPO_CONTRIBUTORS_FAILED';
export const FETCH_REPO_CONTRIBUTORS_FINISHED = 'FETCH_REPO_CONTRIBUTORS_FINISHED';